Feature/inline attachments
DockYard/elixir-mail pull request #137
Opened 2021-10-22 14:20 UTC by jarrodmoldrich

## Changes proposed in this pull request

For parts with `content-dispostion: inline` its important to reorganize the `multipart` arrangement in the adapter.  In particular it needs to be arrange liked this:

```
start multipart/mixed
  start multipart/related
    start multipart/alternative
      <text and html parts>
    end multipart/alternative
    <inline parts>
  end multipart/related
  <attachment parts>
end multipart/mixed
```

My changes reorganize the parts as shown above, while maintaining backwards compatibility.  It also adds matching functions for querying for inline attachments as for regular attachments.  This change was required for inline images and `.ics` files to work properly, particularly in Outlook webmail.

I've stopped short of adding tests to the test suite, and I'll wait for you to validate my approach first.  I duplicated this code for `kalys/bamboo_ses`, where it currently functions well for my use cases: https://github.com/kalys/bamboo_ses/pull/43

Note: This PR also deprecates #133 as the original order of text parts should be maintained

2021-12-11 07:40 UTC, michelson commented
Hi there,

First, thanks for this library. I'm trying this branch, and it works ok; I'm testing it with a set of .eml files, and it is parsed correctly.

the only thing that is missing in this PR is the `get_attachments` function to be able to get both inline and attachments:


it is a little change though:

```ex
  def get_attachments(%Mail.Message{} = message) do
    walk_parts([message], {:cont, []}, fn message, acc ->
      case Mail.Message.is_any_attachment?(message) do
        true ->
          ##### THIS
          case Mail.Message.get_header(message, :content_disposition) do
            ["inline", {"filename", filename}] ->
              {:cont, List.insert_at(acc, -1, {filename, message.body})}
            ["attachment", {"filename", filename}] ->
              {:cont, List.insert_at(acc, -1, {filename, message.body})}
          end
          ###### 
        false ->
          {:cont, acc}
      end
    end)
    |> elem(1)
  end
```

2024-02-04 14:16 UTC, bcardarella commented
@jarrodmoldrich thank you very much apoligies this went stale. I know it's a bit rediculous to ask after years but if you could just add regression tests for the additional behavior added I can merge this in.

2024-05-08 16:48 UTC, Hermanverschooten commented
+1

2024-09-26 21:14 UTC, jarrodmoldrich commented
Sorry, I've been off the radar, but I'm back!  I'll have a look at this in the coming weeks.

2024-10-05 07:31 UTC, gernotkogler commented
+1

2024-11-16 05:56 UTC, jarrodmoldrich commented
@bcardarella Sorry for the delay.  Added some tests.  Let me know if you think this needs anything else.

2024-12-24 05:15 UTC, princemaple commented
Hi @bcardarella do you think this one can go in now?

2024-12-24 05:39 UTC, bcardarella commented
that'lll be @andrewtimberlake's call

2025-01-06 11:28 UTC, andrewtimberlake requested changes
Thanks for this.
I’ve added a few comments/questions and a request for some tests to address my concerns.

2025-01-06 11:28 UTC, andrewtimberlake commented on lib/mail/renderers/rfc_2822.ex
> +    Enum.reduce(message.parts, [[], [], []], fn part, [texts, mixed, inlines] ->
Would it not be better to work with a tuple of lists `{[], [], []}` to be more explicit about the number of lists being generated?

2025-01-06 11:28 UTC, andrewtimberlake commented on lib/mail/renderers/rfc_2822.ex
> +    has_inline = Enum.any?(inlines)
Might it not be more explicit to use `!Enum.empty?(list)` because the behaviour of `Enum.any?/1` and `Enum.all?/1` are not necessarily intuitive when providing empty lists.

2025-01-06 11:28 UTC, andrewtimberlake commented on lib/mail/renderers/rfc_2822.ex
> +    if has_inline || has_mixed_parts do
Do we need multipart/mixed if there are only inline attachments? Shouldn’t it then just be wrapped in related?

2025-01-06 11:28 UTC, andrewtimberlake commented on lib/mail/renderers/rfc_2822.ex
> +      if has_text_parts do
What if it’s only text/html with inline attachments and no text/plain? Then there’s no alternative, right?

2025-01-06 11:28 UTC, andrewtimberlake commented on test/mail/renderers/rfc_2822_test.exs
>  end
I think we need tests for
- only text/html with only inline attachments
- only text/html with only normal attachments
- text/html and text/plain with only inline attachments
- text/html and text/plain with only normal attachments

2025-04-09 08:59 UTC, closed without merging

2025-04-09 09:51 UTC, andrewtimberlake commented
@jarrodmoldrich Thanks for working on this. I ended up going with a different implementation but added you as a co-author on the [commit](https://github.com/DockYard/elixir-mail/commit/f738af707421f6b40358b70e1f6c0bfe6bf6ff39)

2025-04-09 23:17 UTC, jarrodmoldrich commented
@andrewtimberlake Thanks for taking the lead on this.